name: 'Unity - Test runner'
author: Paul Pacheco <paulpach@gmail.com>
description: 'Run unity in batch mode'
inputs: 
  args:
    required: true
    description: 'Arguments to pass to unity'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'box'
  color: 'gray-dark'
