name: CI
on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  testRunnerInEditMode:
    name: Test edit mode 📝
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate license
      - name: Activate Unity
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   

      # Configure test runner
      - name: Run tests
        uses: ./
        with:
          args: -runTests -projectPath unity-project-with-correct-tests
      
      - name: Return License
        if: always()
        uses: ./
        with:
          # Arguments to pass to unity
          args: -returnlicense -quit
